# Generated by Django 4.1 on 2022-08-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timespend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespend',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='api.activitie'),
        ),
    ]
